### PR TITLE
V1 fixes

### LINKED ISSUE #98: Session issues
I've noticed sessions inconsistently logging in and out, and I just found a case where I'm logged in as Howard.

### PR DESCRIPTION
**Pull request by albertcui**
Fixes #98, #102, #63

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -116,29 +116,33 @@ app.use(session({
...
-                if (!match) {
+                if(err || !match) {
                     return next()
-                }
-                else {
+                } else {
                     utility.fillPlayerNames(match.players, function(err) {
                         req.match = match
+                        //Add to cache if we have parsed data
+                        if (match.parsed_data && process.env.NODE_ENV !== "production") {
```
Comment (howardc93) [inline app.js]: noob wrong condition

File: views/index.jade [hunk 2]
```diff
@@ -15,7 +15,7 @@ block content
     p.lead
      | As the name suggests, we're yet <em>another</em> Dota 2 stats site.
     p.lead <strong>But we're special!</strong> (At least we think we are.)
-    p.lead We'll download the replays of your games for you and even parse them to get even more stats!
+    p.lead We'll download the replays of your games for parse them to get even more stats!
```
Comment (howardc93) [inline views/index.jade]: can you even grammar

**Comment by howardc93** [comment]
signoff
